using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.IdentityModel.Tokens;
using OwnID.Extensibility.Json;
using OwnID.Web.Gigya.Contracts;
using OwnID.Web.Gigya.Contracts.Accounts;
using OwnID.Web.Gigya.Contracts.Jwt;
using OwnID.Web.Gigya.Contracts.Login;

namespace OwnID.Web.Gigya.ApiClient
{
    public class GigyaRestApiClient<TProfile> where TProfile : class, IGigyaUserProfile
    {
        private readonly GigyaConfiguration _configuration;
        private readonly HttpClient _httpClient;

        private readonly ConcurrentDictionary<GigyaFields, string> _profileFieldsCache = new();

        public GigyaRestApiClient(GigyaConfiguration configuration, IHttpClientFactory httpClientFactory)
        {
            _configuration = configuration;
            _httpClient = httpClientFactory.CreateClient();
        }

        public async Task<GetAccountInfoResponse<TProfile>> GetUserInfoByUid(string uid)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration);

            if (!string.IsNullOrEmpty(uid))
                parameters.AddParameter("UID", uid);

            var getAccountMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.getAccountInfo"),
                new FormUrlEncodedContent(parameters));

            return
                await OwnIdSerializer.DeserializeAsync<GetAccountInfoResponse<TProfile>>(await getAccountMessage.Content
                    .ReadAsStreamAsync());
        }

        public async Task<BaseGigyaResponse> SetAccountInfoAsync<T>(string did, T profile = null,
            AccountData data = null) where T : class, IGigyaUserProfile
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("UID", did);

            if (profile != null)
                parameters.AddParameter("profile", profile);

            if (data != null)
            {
                foreach (var connection in data.OwnId.Connections.Where(connection =>
                    string.IsNullOrEmpty(connection.Hash)))
                    connection.Hash = connection.PublicKey.GetSha256();

                parameters.AddParameter("data", data);
            }

            var setAccountDataMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.setAccountInfo"),
                new FormUrlEncodedContent(parameters));

            var setAccountResponse = await OwnIdSerializer.DeserializeAsync<BaseGigyaResponse>(
                await setAccountDataMessage.Content
                    .ReadAsStreamAsync());

            return setAccountResponse;
        }

        public async Task<LoginResponse> NotifyLogin(string did, string targetEnvironment = null)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("siteUID", did)
                .AddParameter("skipValidation", bool.TrueString);

            if (!string.IsNullOrEmpty(targetEnvironment))
                parameters.AddParameter("targetEnv", targetEnvironment);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.notifyLogin"),
                new FormUrlEncodedContent(parameters));

            return await OwnIdSerializer.DeserializeAsync<LoginResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        public async Task<JsonWebKey> GetPublicKey()
        {
            var parameters = ParametersFactory.CreateApiKeyParameter(_configuration);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.getJWTPublicKey"),
                new FormUrlEncodedContent(parameters));
            return new JsonWebKey(await responseMessage.Content.ReadAsStringAsync());
        }

        public async Task<GetJwtResponse> GetJwt(string did)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("targetUID", did);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.getJWT"),
                new FormUrlEncodedContent(parameters));
            return await OwnIdSerializer.DeserializeAsync<GetJwtResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        /// <summary>
        ///     Reset account password with resetToken generated by Gigya
        /// </summary>
        /// <param name="resetToken">reset token</param>
        /// <param name="newPassword">new password to set</param>
        /// <returns>
        ///     A task that represents the asynchronous reset password operation.
        ///     The task result contains the <see cref="ResetPasswordResponse" />
        /// </returns>
        /// <remarks>
        ///     Documentation: https://developers.gigya.com/display/GD/accounts.resetPassword+REST
        /// </remarks>
        public async Task<ResetPasswordResponse> ResetPasswordAsync(string resetToken, string newPassword)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("newPassword", newPassword)
                .AddParameter("passwordResetToken", resetToken);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.resetPassword"),
                new FormUrlEncodedContent(parameters));

            return await OwnIdSerializer.DeserializeAsync<ResetPasswordResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        public async Task<BaseGigyaResponse> DeleteAccountAsync(string did)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("UID", did);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.deleteAccount"),
                new FormUrlEncodedContent(parameters));

            return await OwnIdSerializer.DeserializeAsync<BaseGigyaResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        public async Task<UidContainer> SearchByPublicKey(string publicKey,
            GigyaFields fields = GigyaFields.UID | GigyaFields.Connections)
        {
            var objectsToGet = fields | GigyaFields.ConnectionPublicKeys;
            var result =
                await SearchAsync<UidContainer>(GigyaFields.ConnectionPublicKeysHash, publicKey.GetSha256(),
                    objectsToGet);

            if (!result.IsSuccess || (result.First.Data?.OwnId?.Connections?.All(x => x.PublicKey != publicKey) ?? true))
                return null;

            return result.First;
        }

        public async Task<SearchGigyaResponse<TResult>> SearchAsync<TResult>(GigyaFields searchKey, string searchValue,
            GigyaFields resultSet = GigyaFields.UID | GigyaFields.Connections) where TResult : class
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration).AddParameter("query",
                $"SELECT {GetGigyaProfileFields(resultSet)} FROM accounts WHERE {GetGigyaProfileFields(searchKey)} = \"{searchValue}\" LIMIT 1");
            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.search"),
                new FormUrlEncodedContent(parameters));

            var result = await OwnIdSerializer.DeserializeAsync<SearchGigyaResponse<TResult>>(
                await responseMessage.Content.ReadAsStreamAsync());

            return result;
        }

        private string GetGigyaProfileFields(GigyaFields fields)
        {
            if (_profileFieldsCache.TryGetValue(fields, out var result))
                return result;

            var resultFields = new List<string>();

            var enumType = typeof(GigyaFields);
            foreach (var value in Enum.GetValues<GigyaFields>())
            {
                if (!fields.HasFlag(value))
                    continue;

                var memberInfos = enumType.GetMember(value.ToString());

                var enumValueMemberInfo = memberInfos.First(m => m.DeclaringType == enumType);
                var valueAttributes = enumValueMemberInfo.GetCustomAttributes(typeof(GigyaFieldsAttribute), false);

                if (valueAttributes.Length == 0)
                    throw new Exception($"`{nameof(GigyaFields)}.{value}` doesn't has `GigyaFields` attribute");

                var queriedFields = ((GigyaFieldsAttribute) valueAttributes[0]).Fields.Split(",");

                resultFields.AddRange(queriedFields);
            }

            result = string.Join(", ", resultFields
                .Select(x => x.Trim())
                .Distinct()
                .OrderBy(x => x)
                .ToArray());

            _profileFieldsCache.TryAdd(fields, result);

            return result;
        }
    }
}