apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.demo4.dev.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo_dev_4_151850889514
            - name: OWNID__NAME
              value: Noted (OwnID Demo 4)
            - name: OWNID__DESCRIPTION
              value: Noted (OwnID Demo 4)
            - name: OWNID__TFA_ENABLED
              value: 'false'
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo4.dev.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: demo4.dev.ownid.com
            - name: OWNID__MAGIC_LINK__REDIRECT_URL
              value: https://demo4.dev.ownid.com/login
