using System;
using OwnIdSdk.NetCore3.Extensibility.Flow.Contracts.ConnectionRecovery;
using OwnIdSdk.NetCore3.Flow.Steps;

namespace OwnIdSdk.NetCore3.Flow.Interfaces
{
    public interface IJwtComposer
    {
        /// <summary>
        ///     Creates JWT challenge with requested information by OwnId app
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="clientDate">client date</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="did"></param>
        /// <param name="locale">Optional. Content locale</param>
        /// <param name="includeRequester">Optional. Default = false. True if should add requester info to jwt</param>
        /// <returns>Base64 encoded string that contains JWT with hash</returns>
        string GenerateProfileConfigJwt(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            string did, string locale = null, bool includeRequester = false);

        /// <summary>
        ///     Generates JWT for pin step
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="clientDate">client date</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="pin">PIN code generated by <see cref="SetSecurityCode" /></param>
        /// <param name="locale">Optional. Content locale</param>
        /// <returns></returns>
        string GeneratePinStepJwt(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            string pin, string locale = null);

        string GenerateFinalStepJwt(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            string locale = null);

        string GenerateBaseStepJwt(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            string did,
            string locale = null, bool includeRequester = false);

        /// <summary>
        ///     Generates JWT for performing recovery process
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="clientDate">Client date</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="data">Recovery data</param>
        /// <param name="locale">Optional. Content locale</param>
        /// <returns></returns>
        string GenerateRecoveryDataJwt(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            ConnectionRecoveryResult<object> data, string locale = null);
    }
}