using OwnIdSdk.NetCore3.Flow.Steps;

namespace OwnIdSdk.NetCore3.Flow.Interfaces
{
    public interface IJwtComposer
    {
        /// <summary>
        ///     Generates JWT with configuration and user profile for account linking process
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="did">User unique identity</param>
        /// <param name="profile">User profile</param>
        /// <param name="locale">Optional. Content locale</param>
        /// <param name="includeRequester">Optional. Default = false. True if should add requester info to jwt</param>
        /// <returns>Base64 encoded string that contains JWT</returns>
        string GenerateProfileWithConfigDataJwt(string context, FrontendBehavior nextFrontendBehavior, string did,
            object profile,
            string locale = null, bool includeRequester = false);

        /// <summary>
        ///     Creates JWT challenge with requested information by OwnId app
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="locale">Optional. Content locale</param>
        /// <param name="includeRequester">Optional. Default = false. True if should add requester info to jwt</param>
        /// <returns>Base64 encoded string that contains JWT with hash</returns>
        string GenerateProfileConfigJwt(string context, FrontendBehavior nextFrontendBehavior, string did, string locale = null,
            bool includeRequester = false);

        /// <summary>
        ///     Generates JWT for pin step
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="pin">PIN code generated by <see cref="SetSecurityCode" /></param>
        /// <param name="locale">Optional. Content locale</param>
        /// <returns></returns>
        string GeneratePinStepJwt(string context, FrontendBehavior nextFrontendBehavior, string pin,
            string locale = null);

        string GenerateFinalStepJwt(string context, FrontendBehavior nextFrontendBehavior, string locale = null);
        
        string GeneratePartialDidStep(string context, FrontendBehavior nextFrontendBehavior, string did, string locale = null);
    }
}