apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya-<company-name> # <client-name> - name of company, for example nestle
  namespace: prod
  labels:
    app: server-gigya
    appId: <company-name>
spec:
  selector:
    matchLabels:
      app: server-gigya
      appId: <company-name>
  template:
    metadata:
      labels:
        app: server-gigya
        appId: <company-name>
    spec:
      containers:
        - name: server-gigya
          image: server-gigya:latest # path to image, ex: 571861302935.dkr.ecr.us-east-2.amazonaws.com/ownid-server-netcore3-gigya-staging:latest
          ports:
            - containerPort: 5002
          env:
            - name: OWNID__CALLBACK_URL # Public server domain name (CNAME). Example: https://my-company.ownid.com 
              value: https://<company-name>.ownid.com
            - name: OWNID__DID # Unique website identifier. Example: did:my-company:63302f94e20e45a4a3e7a6e5f1863a16
              value: did:<company-name>:<did>
            - name: OWNID__NAME # Website name - will be shown on https://app.ownid.com
              value: <Company name>
            - name: OWNID__DESCRIPTION # Website description - will be shown on https://app.ownid.com
              value: <Company description>
            - name: OWNID__ICON # Website icon - will be shown on https://app.ownid.com
              value: <Company icon base64>
            - name: OWNID__CACHE_TYPE # Type of cache
              value: redis
            - name: OWNID__CACHE_CONFIG # Redis connection string
              value: <redis uri>
            - name: OWNID__PUB_KEY # Website RSA public key 
              value: <website public key>
            - name: OWNID__PRIVATE_KEY # Website RSA private key 
              value: <website private key>
            - name: OWNID__AUTHENTICATION_MODE # Authentication mode: All(OwnID or FIDO2), OwnIdOnly, Fido2Only
              value: All
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL # Passwordless page subdomain (CNAME). Example: https://passwordless.my-company.com
              value: https://passwordless.<website domain>
            - name: OWNID__TOP_DOMAIN # Company domain that Passwordless page is tightened to. Example: my-company.com
              value: <company-domain>
            - name: OWNID__MAGIC_LINK__REDIRECT_URL # Magic Link redirect url. It should lead to web page with referenced OWNID UI SDK
              value: https://my-comany.com/login
            - name: GIGYA__DATA_CENTER # Gigya data center
              value: us1.gigya.com
            - name: GIGYA__SECRET # Gigya secret
              value: <gigya secret>
            - name: GIGYA__API_KEY # Gigya api key
              value: <gigya api key>
            - name: GIGYA__USER_KEY # Gigya user key
              value: <gigya user key>
            - name: Metrics__Enable # Metrics enabled
              value: 'true'
            - name: Metrics__Namespace # AWS Metrics namespace
              value: <namespace>
            - name: AWS__Region # AWS Region
              value: <region>
            - name: AWS__AccessKeyId # AWS access key Id
              value: <access key id>
            - name: AWS__SecretAccessKey # AWS secret access key
              value: <secret access key>
            - name: SMTP__HOST # SMTP Server host
              value: <smtp.my-company.com>
            - name: SMTP__USER_NAME # SMTP Server User Name (auth)
              value: <user name>
            - name: SMTP__PASSWORD # SMTP Server Password (auth)
              value: <password>
            - name: SMTP__SSL # SMTP use secure connection. Default is false
              value: 'false'
            - name: SMTP__FROM_ADDRESS # Use this email like from address 
              value: no-reply@my-company.com
            - name: SMTP__FROM_NAME # Use this like from user friendly name 
              value: Magic Link - My Company   
            