//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwnID.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OwnIdSdkDefault {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnIdSdkDefault() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OwnID.Web.Resources.OwnIdSdkDefault", typeof(OwnIdSdkDefault).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        internal static string Field__0__is_required {
            get {
                return ResourceManager.GetString("Field {0} is required", resourceCulture);
            }
        }
        
        internal static string Field__0__has_incorrect_format {
            get {
                return ResourceManager.GetString("Field {0} has incorrect format", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_a_string_or_array_type_with_a_maximum_length_of___1__ {
            get {
                return ResourceManager.GetString("The field {0} must be a string or array type with a maximum length of \'{1}\'", resourceCulture);
            }
        }
        
        internal static string Error_PhoneAlreadyConnected {
            get {
                return ResourceManager.GetString("Error_PhoneAlreadyConnected", resourceCulture);
            }
        }
        
        internal static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        internal static string Error_RequiresBiometricInput {
            get {
                return ResourceManager.GetString("Error_RequiresBiometricInput", resourceCulture);
            }
        }
        
        internal static string Error_RecoveryTokenExpired {
            get {
                return ResourceManager.GetString("Error_RecoveryTokenExpired", resourceCulture);
            }
        }
        
        internal static string Error_UserCanceledAuth {
            get {
                return ResourceManager.GetString("Error_UserCanceledAuth", resourceCulture);
            }
        }
        
        internal static string Email_MagicLink_Body {
            get {
                return ResourceManager.GetString("Email_MagicLink_Body", resourceCulture);
            }
        }
        
        internal static string Email_MagicLink_Subject {
            get {
                return ResourceManager.GetString("Email_MagicLink_Subject", resourceCulture);
            }
        }
        
        internal static string Error_MagicLink_SameBrowser {
            get {
                return ResourceManager.GetString("Error_MagicLink_SameBrowser", resourceCulture);
            }
        }
    }
}
