apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.demo.staging.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo_staging_151850889514
            - name: OWNID__NAME
              value: Noted (OwnID Demo)
            - name: OWNID__DESCRIPTION
              value: Noted (OwnID Demo)
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo.staging.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: demo.staging.ownid.com
            - name: OWNID__MAGIC_LINK__REDIRECT_URL
              value: https://demo.staging.ownid.com/login