using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using OwnIdSdk.NetCore3.Cryptography;
using OwnIdSdk.NetCore3.Extensibility.Configuration;
using OwnIdSdk.NetCore3.Extensibility.Services;
using OwnIdSdk.NetCore3.Flow.Interfaces;
using OwnIdSdk.NetCore3.Flow.Steps;

namespace OwnIdSdk.NetCore3.Flow
{
    /// <inheritdoc cref="IJwtComposer" />
    public class JwtComposer : IJwtComposer
    {
        private readonly IJwtService _jwtService;
        private readonly ILocalizationService _localizationService;
        private readonly IOwnIdCoreConfiguration _ownIdCoreConfiguration;

        /// <summary>
        /// </summary>
        /// <param name="ownIdCoreConfiguration">Core configuration to be used</param>
        /// <param name="jwtService">Service for generating JWT</param>
        /// <param name="localizationService">Optional(only if localization is needed). Localization service</param>
        public JwtComposer([NotNull] IOwnIdCoreConfiguration ownIdCoreConfiguration,
            [NotNull] IJwtService jwtService, ILocalizationService localizationService)
        {
            _jwtService = jwtService;
            _localizationService = localizationService;
            _ownIdCoreConfiguration = ownIdCoreConfiguration;
        }

        /// <summary>
        ///     Creates JWT challenge with requested information by OwnId app
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="clientDate">client date</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="did">User unique identifier</param>
        /// <param name="locale">Optional. Content locale</param>
        /// <param name="includeRequester">Optional. Default = false. True if should add requester info to jwt</param>
        /// <returns>Base64 encoded string that contains JWT with hash</returns>
        public string GenerateProfileConfigJwt(string context, DateTime? clientDate,
            FrontendBehavior nextFrontendBehavior, string did,
            string locale = null, bool includeRequester = false)
        {
            var data = GetFieldsConfigDictionary(did);

            if (includeRequester)
            {
                var (key, value) = GetRequester();
                data[key] = value;
            }

            var fields = GetBaseFlowFieldsDictionary(context, nextFrontendBehavior, data,
                locale);

            return _jwtService.GenerateDataJwt(fields, clientDate);
        }

        /// <summary>
        ///     Generates JWT for pin step
        /// </summary>
        /// <param name="context">Challenge Unique identifier</param>
        /// <param name="clientDate">client date</param>
        /// <param name="nextFrontendBehavior">Next flow step description</param>
        /// <param name="pin">PIN code generated by <see cref="SetSecurityCode" /></param>
        /// <param name="locale">Optional. Content locale</param>
        /// <returns></returns>
        public string GeneratePinStepJwt(string context, DateTime? clientDate,
            FrontendBehavior nextFrontendBehavior, string pin,
            string locale = null)
        {
            var requester = GetRequester();

            var data = new Dictionary<string, object>
            {
                {"pin", pin},
                {requester.Key, requester.Value}
            };

            var fields = GetBaseFlowFieldsDictionary(context, nextFrontendBehavior, data, locale);
            return _jwtService.GenerateDataJwt(fields, clientDate);
        }

        public string GenerateFinalStepJwt(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            string locale = null)
        {
            var fields = GetBaseFlowFieldsDictionary(context, nextFrontendBehavior, null, locale);
            return _jwtService.GenerateDataJwt(fields, clientDate);
        }

        public string GenerateBaseStep(string context, DateTime? clientDate, FrontendBehavior nextFrontendBehavior,
            string did, string locale = null, bool includeRequester = false)
        {
            var (didKey, didValue) = GetDid(did);

            var data = new Dictionary<string, object>
            {
                {didKey, didValue},
                {"requestedFields", new object[0]}
            };

            if (includeRequester)
            {
                var (reqKey, reqValue) = GetRequester();
                data.Add(reqKey, reqValue);
            }

            var fields = GetBaseFlowFieldsDictionary(context, nextFrontendBehavior, data, locale);

            return _jwtService.GenerateDataJwt(fields, clientDate);
        }

        private Dictionary<string, object> GetBaseFlowFieldsDictionary(string context,
            FrontendBehavior nextFrontendBehavior, object data = null, string locale = null)
        {
            var stepType = nextFrontendBehavior.Type.ToString();
            var actionType = nextFrontendBehavior.ActionType.ToString();
            var stepDict = new Dictionary<string, object>
            {
                {"type", stepType.First().ToString().ToLowerInvariant() + stepType.Substring(1)},
                {"actionType", actionType.First().ToString().ToLowerInvariant() + actionType.Substring(1)},
                {"challengeType", nextFrontendBehavior.ChallengeType.ToString().ToLowerInvariant()}
            };

            if (nextFrontendBehavior.Polling != null)
                stepDict.Add("polling", new
                {
                    url = nextFrontendBehavior.Polling.Url.ToString(),
                    method = nextFrontendBehavior.Polling.Method,
                    interval = nextFrontendBehavior.Polling.Interval
                });

            if (nextFrontendBehavior.Callback != null)
                stepDict.Add("callback", new
                {
                    url = nextFrontendBehavior.Callback.Url,
                    method = nextFrontendBehavior.Callback.Method
                });

            var fields = new Dictionary<string, object>
            {
                {"jti", context},
                {"locale", locale},
                {"nextStep", stepDict}
            };

            if (data != null)
                fields.Add("data", data);

            return fields;
        }

        private Dictionary<string, object> GetFieldsConfigDictionary(string did)
        {
            var dataFields = new Dictionary<string, object>
            {
                {
                    // TODO : PROFILE
                    "requestedFields", _ownIdCoreConfiguration.ProfileConfiguration.ProfileFieldMetadata.Select(x =>
                    {
                        var label = Localize(x.Label);

                        return new
                        {
                            type = x.Type,
                            key = x.Key,
                            label,
                            placeholder = Localize(x.Placeholder),
                            validators = x.Validators.Select(v => new
                            {
                                type = v.Type,
                                errorMessage =
                                    v.NeedsInternalLocalization
                                        ? v.FormatErrorMessage(label, Localize(v.ErrorKey))
                                        : v.FormatErrorMessage(label),
                                parameters = v.Parameters
                            })
                        };
                    })
                }
            };

            var (didKey, didValue) = GetDid(did);
            dataFields.Add(didKey, didValue);

            return dataFields;
        }

        private KeyValuePair<string, string> GetDid(string did)
        {
            return new KeyValuePair<string, string>("did", did);
        }

        private KeyValuePair<string, object> GetRequester()
        {
            return new KeyValuePair<string, object>("requester", new
            {
                did = _ownIdCoreConfiguration.DID,
                pubKey = RsaHelper.ExportPublicKeyToPkcsFormattedString(_ownIdCoreConfiguration
                    .JwtSignCredentials),
                name = Localize(_ownIdCoreConfiguration.Name),
                icon = _ownIdCoreConfiguration.Icon,
                description = Localize(_ownIdCoreConfiguration.Description),
                overwriteFields = _ownIdCoreConfiguration.OverwriteFields
            });
        }

        private string Localize(string key)
        {
            return _localizationService?.GetLocalizedString(key) ?? key;
        }
    }
}