using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.IdentityModel.Tokens;
using OwnIdSdk.NetCore3.Web.Gigya.Contracts;
using OwnIdSdk.NetCore3.Web.Gigya.Contracts.Accounts;
using OwnIdSdk.NetCore3.Web.Gigya.Contracts.Jwt;
using OwnIdSdk.NetCore3.Web.Gigya.Contracts.Login;
using OwnIdSdk.NetCore3.Web.Gigya.Contracts.UpdateProfile;
using OwnIdSdk.NetCore3.Web.Gigya.Json;

namespace OwnIdSdk.NetCore3.Web.Gigya.ApiClient
{
    public class GigyaRestApiClient
    {
        private readonly GigyaConfiguration _configuration;
        private readonly HttpClient _httpClient;

        public GigyaRestApiClient(GigyaConfiguration configuration, IHttpClientFactory httpClientFactory)
        {
            _configuration = configuration;
            _httpClient = httpClientFactory.CreateClient();
        }

        public async Task<GetAccountInfoResponse> GetUserInfoByUid(string uid)
        {
            return await GetUserProfile(uid);
        }

        public async Task<GetAccountInfoResponse> GetUserInfoByToken(string regToken)
        {
            return await GetUserProfile(regToken: regToken);
        }

        public async Task<BaseGigyaResponse> SetAccountInfo(string did, GigyaUserProfile profile = null,
            AccountData data = null)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("UID", did);

            if (profile != null)
                parameters.AddParameter("profile", profile);

            if (data != null)
                parameters.AddParameter("data", data);

            var setAccountDataMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.setAccountInfo"),
                new FormUrlEncodedContent(parameters));

            var setAccountResponse = await JsonSerializer.DeserializeAsync<BaseGigyaResponse>(
                await setAccountDataMessage.Content
                    .ReadAsStreamAsync());

            return setAccountResponse;
        }

        public async Task<LoginResponse> NotifyLogin(string did, string targetEnvironment = null)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("siteUID", did)
                .AddParameter("skipValidation", Boolean.TrueString);

            if (!string.IsNullOrEmpty(targetEnvironment))
                parameters.AddParameter("targetEnv", targetEnvironment);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.notifyLogin"),
                new FormUrlEncodedContent(parameters));

            return await JsonSerializer.DeserializeAsync<LoginResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        public async Task<JsonWebKey> GetPublicKey()
        {
            var parameters = ParametersFactory.CreateApiKeyParameter(_configuration);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.getJWTPublicKey"),
                new FormUrlEncodedContent(parameters));
            return new JsonWebKey(await responseMessage.Content.ReadAsStringAsync());
        }

        public async Task<GetJwtResponse> GetJwt(string did)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("targetUID", did);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.getJWT"),
                new FormUrlEncodedContent(parameters));
            return await JsonSerializer.DeserializeAsync<GetJwtResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        /// <summary>
        /// Reset account password with resetToken generated by Gigya
        /// </summary>
        /// <param name="resetToken">reset token</param>
        /// <param name="newPassword">new password to set</param>
        /// <returns>
        /// A task that represents the asynchronous reset password operation.
        /// The task result contains the <see cref="ResetPasswordResponse"/>
        /// </returns>
        /// <remarks>
        /// Documentation: https://developers.gigya.com/display/GD/accounts.resetPassword+REST
        /// </remarks>
        public async Task<ResetPasswordResponse> ResetPasswordAsync(string resetToken, string newPassword)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("newPassword", newPassword)
                .AddParameter("passwordResetToken", resetToken);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.resetPassword"),
                new FormUrlEncodedContent(parameters));

            return await JsonSerializer.DeserializeAsync<ResetPasswordResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        public async Task<BaseGigyaResponse> DeleteAccountAsync(string did)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration)
                .AddParameter("UID", did);

            var responseMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.deleteAccount"),
                new FormUrlEncodedContent(parameters));

            return await JsonSerializer.DeserializeAsync<BaseGigyaResponse>(
                await responseMessage.Content.ReadAsStreamAsync());
        }

        private async Task<GetAccountInfoResponse> GetUserProfile(string uid = null, string regToken = null)
        {
            var parameters = ParametersFactory.CreateAuthParameters(_configuration);

            if (!String.IsNullOrEmpty(uid))
                parameters.AddParameter("UID", uid);
            else
                parameters.AddParameter("regToken", regToken);

            var getAccountMessage = await _httpClient.PostAsync(
                new Uri($"https://accounts.{_configuration.DataCenter}/accounts.getAccountInfo"),
                new FormUrlEncodedContent(parameters));

            var serializerOptions = new JsonSerializerOptions();
            serializerOptions.Converters.Add(new AutoPrimitiveToStringConverter());

            return
                await JsonSerializer.DeserializeAsync<GetAccountInfoResponse>(await getAccountMessage.Content
                    .ReadAsStreamAsync(), serializerOptions);
        }
    }
}